%% generatorPage.m
% Creates the layout for the signal generator page.
function generatorPage()
    generatorContainer = figure('Name', 'Signal Generator - Generate', ...
        'Units', 'normalized', ...
        'NumberTitle', 'off', ...
        'Position', [0.2 0.2 0.6 0.6] ...
    );
end