%% homePage.m
% Creates the layout for the home page.
function homePage()
    mainContainer = figure('Name','Signal Generator', ...
        'Units', 'normalized', ...
        'NumberTitle', 'off', ...
        'Position', [0.2 0.2 0.6 0.6] ...
    );
    
    docsToolbar = uimenu(mainContainer, 'Text', 'Documentation');
        % Open .docx
        uimenu(docsToolbar, ...
            "Text", 'Open Documentation - .docx', ...
            "Accelerator",  'D', ...
            "Callback", 'open("Signal Generator - Documentation.docx")' ...
        );
        % Open .pdf
        uimenu(docsToolbar, ...
            "Text", 'Open Documentation - .pdf', ...
            "Accelerator",  'P', ...
            "Callback", 'open("Signal Generator - Documentation.pdf")' ...
            ...
        );
end