%% homePage.m
% Creates the layout for the home page.
function homePage()
    mainContainer = figure('Name','Signal Generator', ...
        'Units', 'normalized', ...
        'NumberTitle', 'off', ...
        'Resize', 'off', ...
        'Position', [0.25 0.25 0.5 0.5] ...
    );
    
    documentationToolbar(mainContainer);

    % --- UI ---

    title();
    subtitle();

    buttons();

    footer();
end

%% documentationToolbar
% Adds the "Documentation" toolbar item
function docsToolbar = documentationToolbar(mainContainer)
    docsToolbar = uimenu(mainContainer, 'Text', 'Documentation');

    % Open .docx
    uimenu(docsToolbar, ...
        "Text", 'Open Documentation - .docx', ...
        "Accelerator",  'D', ...
        "Callback", 'openDocs("docx")' ...
    );
    % Open .pdf
    uimenu(docsToolbar, ...
        "Text", 'Open Documentation - .pdf', ...
        "Accelerator",  'P', ...
        "Callback", 'openDocs("pdf")' ...
        ...
    );
end

%% title
% Adds the title to the page
function titleText = title()
    titleText = uicontrol('Style','text', ...
        'Units', 'normalized', ...
        'Fontsize', 36, ...
        'FontWeight', 'bold', ...
        'Position',[0.13 0.8 0.35 0.1], ...
        'String','Signal Generator' ...
    );

end

%% subtitle
% Adds the title to the page
function subtitleText = subtitle()
    subtitleText = uicontrol('Style','text', ...
        'Units', 'normalized', ...
        'Fontsize', 18, ...
        'Position',[0.045 0.72 0.7 0.1], ...
        'String','Generate a signal composed of one or more harmonics.' ...
    );
end

%% buttons
% Adds the controls (push buttons) to the page, and registers their callbacks
function buttons()
    uicontrol('Style','pushbutton', ...
        'Units', 'normalized', ...
        'Fontsize', 16, ...
        'FontWeight', 'bold', ...
        'ForegroundColor', '#ed853d', ...
        'Position',[0.14 0.5 0.45 0.1], ...
        'String','Open Generator', ...
        'Callback', 'generatorPage()' ...
    );

    uicontrol('Style','pushbutton', ...
        'Units', 'normalized', ...
        'Fontsize', 12, ...
        'ForegroundColor', '#0f3d8d', ...
        'Position',[0.14 0.26 0.3 0.06], ...
        'String','Open Documentation (.docx)', ...
        'Callback', 'openDocs("docx")' ...
    );

    uicontrol('Style','pushbutton', ...
        'Units','normalized', ...
        'Fontsize', 12, ...
        'ForegroundColor', '#af0c02', ...
        'Position',[0.14 0.2 0.3 0.06], ...
        'String','Open Documentation (.pdf)', ...
        'Callback', 'openDocs("pdf")' ...
    );
end

%% footer
% Adds the footer text to the bottom of the page
function footerText = footer()
    footerText = uicontrol('Style','text', ...
        'Units', 'normalized', ...
        'Fontsize', 12, ...
        'FontAngle', 'italic', ...
        'Position',[0.45 -0.05 0.72 0.1], ...
        'String','Author: David Pescariu - Final project for CAG 2024-2025' ...
    );
end
